const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '..');
const outputPath = path.join(projectRoot, 'app.bundle.js');
const sourceFiles = [
  'js/lib/constants.js',
  'js/lib/format.js',
  'js/lib/date.js',
  'js/lib/csv.js',
  'js/lib/storage.js',
  'js/domain/portfolio.js',
  'js/domain/retirement.js',
  'js/domain/dividends.js',
  'js/domain/market.js',
  'js/domain/backup.js',
  'js/domain/transaction-import.js',
  'js/repositories/browser.js',
  'js/services/finmind.js',
  'js/components/confirmation.js',
  'js/components/toast.js',
  'js/app/router.js',
  'app.js',
];

function transformSource(file, source) {
  let result = source.replace(/^import .*;\n/gm, '').replace(/^export /gm, '');
  // app.js intentionally wraps this pure function to inject the current calendar.
  if (file === 'js/lib/date.js') result = result.replace('function marketTargetDate', 'function resolveMarketTargetDate');
  return result.trim();
}

function buildBundle() {
  const body = sourceFiles.map(file => {
    const source = fs.readFileSync(path.join(projectRoot, file), 'utf8');
    return `// Source: ${file}\n${transformSource(file, source)}`;
  }).join('\n\n');
  return `// Generated by scripts/build-static.cjs. Do not edit directly.\n// This classic-script build supports direct file:// use and GitHub Pages.\n\n${body}\n`;
}

const bundle = buildBundle();
if (process.argv.includes('--check')) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : '';
  if (current !== bundle) {
    console.error('app.bundle.js is out of date; run: node scripts/build-static.cjs');
    process.exitCode = 1;
  } else {
    console.log('static bundle: up to date');
  }
} else {
  fs.writeFileSync(outputPath, bundle);
  console.log(`built ${path.relative(projectRoot, outputPath)}`);
}

module.exports = { buildBundle, sourceFiles };
